### ISSUE TITLE
Custom message based on api response

### ISSUE THREAD

**Issue by radumro** [kennym/cf7-to-api#14]
Hi, how can i give custom messages based on api result?

i have 2 cases 
1. the api service is not available.
   the redirect page is set to go to the success  page regardless of the api response
2. if the sesponce from api has errors that the user need to fix how can i pass this messages back to the form?

thanks

**Comment by kennym** [comment]
> the api service is not available.
the redirect page is set to go to the success page regardless of the api response
This is not handled yet - I'm glad to accept any PRs

> if the sesponce from api has errors that the user need to fix how can i pass this messages back to the form?
Currently you can't.
