### ISSUE TITLE
Special Mail Tags not working

### ISSUE THREAD

**Issue by Zetanova** [kennym/cf7-to-api#15]
Special mail tags of wp cf7 are all empty:
https://contactform7.com/special-mail-tags/

Tested with [_serial_number] and [_post_id]

**Comment by kennym** [comment]
@Zetanova should your latest PR fix that?

**Comment by Zetanova** [comment]
@kennym it is a different issue, cf7 provides the values. 
Maybe they are in an other collection or they are inserted/replaced in the next hook

Currently they placeholders get removed with an empty string, 
because they key is not found in `$submited_data[$form_key]`

**Comment by kennym** [comment]
Feel free to submit a PR, if you think you can fix that! :-)

**Comment by Zetanova** [comment]
i want only to report it.

I dont have (don't want) the knowledge of the cf7 plugin to resolve it.
