### ISSUE TITLE
Need examples of API CALL?

### ISSUE THREAD

**Issue by Fx2go** [kennym/cf7-to-api#16]
Hello Kennym,
I'm very happy to use this ambitious plugin.
But I need examples to  write API CALLS.
Do you have cases with input type = "Parameters-GEST-POT" or "json" ?
My need is to  add events (tribe) from a front-end form.
![api_integration](https://user-images.githubusercontent.com/24325046/82911993-d3fbcb80-9f6c-11ea-9f0f-cc1fbeba3756.png)
![last-api-call](https://user-images.githubusercontent.com/24325046/82912008-d6f6bc00-9f6c-11ea-8239-b1290975313e.png)

**Comment by kennym** [comment]
Please hire someone to fix that issue for you. I cannot provide support for your issue. Thanks for understanding. PRs are welcomed.
