### ISSUE TITLE
Checkbox tags not working

### ISSUE THREAD

**Issue by Daniel-E-Davies** [kennym/cf7-to-api#19]
Hi There, 

When I create a checkbox, CF7-to-api seems to create its own tags that are in the format [name-checkboxlabel], however when I use those tags in my JSON, they never appear to resolve to anything but an empty string. Any idea what is happening? 

As an aside, when i make the group of checkboxes a required field, it changes the way the tags are created, CF7-to-API only registers one tag which is just [name]. It doesn't seem like these two actions should be related.

This is whay my checkbox looks like in CF7:

[checkbox Budget "$750,000 - $999,999|280278" "$1,000,000 - $1,249,999|280279" "$1,250,000 - $1,499,999|280280" "$1,500,000 - $1,749,999|280281"]

It gives me tags like this:

[Budget-$750,000 - $999,999]

Am i using this wrong? or is there a bug?

**Comment by kennym** [comment]
Please hire someone to fix that issue for you. I cannot provide support for your issue. Thanks for understanding. PRs are welcomed.
