### ISSUE TITLE
Could not parse external plugin shortcode to api

### ISSUE THREAD

**Issue by baldawayash15** [kennym/cf7-to-api#2]
Hey author,
The plugin works wonderful. But I have an issue with the plugin. I am using International Telephone Input for contact form 7 which uses mail tags to display the output. In the mail tag the shortcode works but it does not parses to api params instead it displays the same shortcode in the debug params. How can I resolve this? I know this plugin is only intended to work with CF7 but how can I achieve this to work with external plugin which are made to work with CF7 that can parse their shortcodes?

**Comment by mindprint** [comment]
I am in a similar pickle. I wanted to use CF7 special tags like `[_remote_ip]`. It just prints the shortcode. Any advice or updates coming up?

**Comment by kennym** [comment]
I currently cannot fix these issues, but I'm happy to accept a PR and deploy those changes.
