### ISSUE TITLE
Bug Report - API Call not accepting Array Value

### ISSUE THREAD

**Issue by kennyryan** [kennym/cf7-to-api#22]
Hi Dev Team,

Very nice plugin and useful. Thank you for your effort!

I want to report a bug, for the multiple select boxes on CF7, this plugin is not accepting the Array from the field. It is only passing the first element of the array via REST.

Example, if the field "Months" contains the array "[0]=> Jan, [1] => Feb, [2] => Mar", the plugin will only send "Jan" in the API call.

Hopefully, we can get this issue fix!

Thank you!

Regards,
Kenny C

**Comment by kennyryan** [comment]
Bug location:
wp-content/plugins/cf7-to-api-basic-auth/includes/class-cf7-api-admin.php

Under get_record( $submission , $qs_cf7_data_map , $type = "params", $template = "" ) function

rather than using $value = reset($value), using a for each loop to combine the array strings into one string.

**Comment by kennyryan** [comment]
![image](https://user-images.githubusercontent.com/13826222/97641938-f9e54900-1a93-11eb-97f1-d7ce6d417a76.png)

**Comment by kennym** [comment]
@kennyryan feel free to submit a PR

**Comment by shaktimanpurush** [comment]
hi, I tried applying the code @kennyryan , but unfortunately it does not work.
When a checkbox has multiple values, only the first value is sent to API.

How can this be solved  ?

**Comment by kennym** [comment]
Please hire someone to fix that issue for you. I cannot provide support for your issue. Thanks for understanding. PRs are welcomed.
