### ISSUE TITLE
How to pass other authentication parameters ?

### ISSUE THREAD

**Issue by apcloic** [kennym/cf7-to-api#23]
Hi,

Thanks a lot for this plugin !

I'm trying to POST form data to a Yetiforce CRM (Open Source) using REST API.
https://doc.yetiforce.com/api/

Here's a working demo php script :
https://github.com/YetiForceCompany/YetiForceScripts/tree/master/YetiREST

As you may notice, the following parameters are required :
'apiPath' => 'https://gitdeveloper.yetiforce.com/',
'wsAppName' => 'portal',
'wsAppPass' => 'portal',
'wsApiKey' => 'VMUwRByXHSq1bLW485ikfvcC97P6gJsz',
'wsUserName' => 'demo@yetiforce.com',
'wsUserPass' => 'demo',

Does anybody knows how to add these extra parameters ?

Regards,

**Comment by kennym** [comment]
Please hire someone to fix that issue for you. I cannot provide support for your issue. Thanks for understanding. PRs are welcomed.
