### ISSUE TITLE
API call not working.

### ISSUE THREAD

**Issue by pawanrajput007** [kennym/cf7-to-api#26]
I'm trying to integrated with marketo API and using following setting.

[https://[munchkinID].mktorest.com/identity/oauth/token/rest/v1/leads.json]https://[munchkinID].mktorest.com/identity/oauth/token/rest/v1/leads.json
Input type - JSON (We have tried Parameters - GET/POST also)
Method - POST

Some time its shows 

[body] => {"requestId":"8dd7#176947dc2a7","success":false,"errors":[{"code":"1003","message":"Leads not specified"}]}

And some time its work but we are not able to see leads in marketo admin.

I have checked with marketo support team and they are not receiving any request. In postman API is working as expected.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/7055157/103525093-af71b580-4ea4-11eb-8212-5ff9b584e0cb.png)

**Comment by kennym** [comment]
Please hire someone to fix that issue for you. I cannot provide support for your issue. Thanks for understanding. PRs are welcomed.
