### ISSUE TITLE
Double quotation marks in field breaks api call

### ISSUE THREAD

**Issue by bugraceylan** [kennym/cf7-to-api#28]
Any field containing double quotation marks breaks the api call, tried with 1.4.6, anyone having this issue? JSON Post is the method.

**Comment by bugraceylan** [comment]
adding $value = str_replace('"', ' ', $value); fixed my issue

**Comment by kennym** [comment]
I cannot provide support for your issue. Thanks for understanding. PRs are welcomed.

**Comment by bugraceylan** [comment]
Hi @kennym , PR 29 were containing the related fix, thanks!
