### ISSUE TITLE
checkbox: multiple values not parsed

### ISSUE THREAD

**Issue by shaktimanpurush** [kennym/cf7-to-api#31]
Hi,

When I use [my-checkbox], and multiple values are checked, only the first item is parsed in the XML to the API with basic auth.

Any ideas on how to fix this ?

Is this plugin here better updated and supported then the mothballed version on Wordpress itself ( no author responses and no updates )?

Thanks

**Comment by kennym** [comment]
Please hire someone to fix that issue for you. I cannot provide support for your issue. Thanks for understanding. PRs are welcomed.
