### ISSUE TITLE
Error with post json

### ISSUE THREAD

**Issue by drbelt27** [kennym/cf7-to-api#33]
i ha tried this plugin, but i have the problem 
i call with basic auth my crm and i setup the json in the plugin but i have returned this error.

error:
Array
(
    [0] => WP_Error Object
        (
            [errors] => Array
                (
                    [json-error] => Array
                        (
                            [0] => 4
                        )

                )

            [error_data] => Array
                (
                )

            [additional_data:protected] => Array
                (
                )

        )

)

_________________________________
json:
{"elementType":"Leads", "element": "{\"company\":\"[text-301]\",\"firstname\":\"[text-302]\",\"lastname\":\"[text-303]\",\"email\":\"[email-497]\",\"phone\":\"[tel-497]\",\"accounttype\":\"[menu-429]\",\"cf_mke_1055\":\"[menu-874]\",\"gdpr_privacypolicy\":\"[acceptance-5]\",\"leadsource\":\"[lead_source]\",\"cf_mke_1056\":\"[language]\"}"}

**Comment by kennym** [comment]
What are the payloads you are providing?

**Comment by drbelt27** [comment]
what is the payload ? 
sorry :(

**Comment by drbelt27** [comment]
sorry in my first message i have paste the incorrect json. you find the correct json below (i use the escape caracter)
{'elementType':'Leads', 
    'element': '{\'company\':\'[text-301]\',\'firstname\':\'[text-302]\',\'lastname\':\'[text-303]\',\'email\':\'[email-497]\',\'phone\':\'[tel-497]\',\'accounttype\':\'[menu-429]\',\'cf_mke_1055\':\'[menu-874]\',\'gdpr_privacypolicy\':\'[acceptance-5]\',\'leadsource\':\'[lead_source]\',\'cf_mke_1056\':\'[language]\'}'
    }

**Comment by jhaeger** [comment]
I've got the same error.

**Comment by jhaeger** [comment]
@drbelt27 

Try the below: 
`{"elementType":"Leads","element":{"company":"[text-301]","firstname":"[text-302]","lastname":"[text-303]","email":"[email-497]","phone":"[tel-497]","accounttype":"[menu-429]","cf_mke_1055":"[menu-874]","gdpr_privacypolicy":"[acceptance-5]","leadsource":"[lead_source]","cf_mke_1056":"[language]"}}`

My issue was improperly formatted JSON. Yours is as well.
