### ISSUE TITLE
The plugin cannot be Activated on WordPress 5.2.2 

### ISSUE THREAD

**Issue by chelder86** [kennym/cf7-to-api#4]
Hi. Thanks for your plugin!!

I've installed the plugin from Plugins - New plugin. 

Unfortunately, when I click on Activate, it just keep disabled (no error is returned).

The plugin Contact form 7 to api + Basic auth v1.3.0 installed is this: https://es.wordpress.org/plugins/cf7-to-api-basic-auth/ 
I'm using WordPress 5.2.2 and Contact Form 7 Version 5.1.3

Note: I've also asked this question here: https://wordpress.org/support/topic/the-plugin-cannot-be-activated-on-wordpress-5-2-2/

**Comment by kennym** [comment]
I cannot fix this right now, but when I get a chance I will.

PRs welcome.

**Comment by srinisubramanian** [comment]
The error I have is as follows:

Warning: require_once(/var/www/site/wp-content/plugins/cf7-to-api-basic-auth/includes/class.cf7-api.php): failed to open stream: No such file or directory in /var/www/site/wp-content/plugins/cf7-to-api-basic-auth/contact-form-7-api.php on line 49

Fatal error: require_once(): Failed opening required '/var/www/site/wp-content/plugins/cf7-to-api-basic-auth/includes/class.cf7-api.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/site/wp-content/plugins/cf7-to-api-basic-auth/contact-form-7-api.php on line 49

**Comment by kennym** [comment]
I currently cannot fix these issues, but I'm happy to accept a PR and deploy those changes.

**Comment by sven09** [comment]
Change 
**QS_CF7_API_INCLUDES_PATH** 
in https://github.com/kennym/cf7-to-api/blob/master/contact-form-7-api.php in line 29
to
`define( 'QS_CF7_API_INCLUDES_PATH' , plugin_dir_path( __FILE__ ));`

Will fix it, because the plugin downloaded vie WP Plugin install has no "includes" directory.

**Comment by kennym** [comment]
@sven09 thank you! Fixed.

**Comment by daniebker** [comment]
I'm getting this error on install for wordpress 5.3.2.

I tried downloading source and zipping and installing from wordpress plugin directly from my wordpress site. In the plugin folder I see an includes folder so reverting this commit (https://github.com/kennym/cf7-to-api/commit/7ef8dcd269e9420d897965626e57b11a8a7a91ba#diff-0dc95e3202da0f75d99561268150ad64) fixed the issue for me and I was able to activate
