### ISSUE TITLE
adding "/" each time the form is saved

### ISSUE THREAD

**Issue by macra** [kennym/cf7-to-api#47]
The plugin has started adding "/"'s in the JSON template every time the form is resaved after changes.

eg;
**Original template:**
{
   "customer_name":"WP Update test",
   "customer_billing_email":"test@example.com",
   "customer_email":"tasty@testy.com",
   "customer_login":"astarisborn",
   "customer_password":"somepasswordnotused",
   "customer_dob":"1953-10-14",
   "customer_street":"100 Devon Street East",
}
**After save 1:**
{
   \"customer_name\":\"WP Update test\",
   \"customer_billing_email\":\"test@example.com\",
   \"customer_email\":\"tasty@testy.com\",
   \"customer_login\":\"astarisborn\",
   \"customer_password\":\"somepasswordnotused\",
   \"customer_dob\":\"1953-10-14\",
   \"customer_street\":\"100 Devon Street East\",
}
**After save 2:**
{
   \\\"customer_name\\\":\\\"WP Update test\\\",
   \\\"customer_billing_email\\\":\\\"test@example.com\\\",
   \\\"customer_email\\\":\\\"tasty@testy.com\\\",
   \\\"customer_login\\\":\\\"astarisborn\\\",
   \\\"customer_password\\\":\\\"somepasswordnotused\\\",
   \\\"customer_dob\\\":\\\"1953-10-14\\\",
   \\\"customer_street\\\":\\\"100 Devon Street East\\\",
}

**After save 3:**
{
   \\\\\\\"customer_name\\\\\\\":\\\\\\\"WP Update test\\\\\\\",
   \\\\\\\"customer_billing_email\\\\\\\":\\\\\\\"test@example.com\\\\\\\",
   \\\\\\\"customer_email\\\\\\\":\\\\\\\"tasty@testy.com\\\\\\\",
   \\\\\\\"customer_login\\\\\\\":\\\\\\\"astarisborn\\\\\\\",
   \\\\\\\"customer_password\\\\\\\":\\\\\\\"somepasswordnotused\\\\\\\",
   \\\\\\\"customer_dob\\\\\\\":\\\\\\\"1953-10-14\\\\\\\",
   \\\\\\\"customer_street\\\\\\\":\\\\\\\"100 Devon Street East\\\\\\\",
}

etc.etc.

I'm in a bit of a panic, as an important project involving 4000 customers due to be deployed on Monday, started doing this today!! Help!!

**Comment by fixinggenie** [comment]
@macra Found it - https://github.com/takayukister/contact-form-7/blob/7684edc91e5b01b280c770179385c80f5376cbeb/includes/contact-form-functions.php#L226

**Comment by studiovanzwet** [comment]
@fixinggenie @macra 
I'm having the same problem, is there a solution to this issue?

**Comment by sstraus** [comment]
Any fix for this problem?

**Comment by studiovanzwet** [comment]
> Any fix for this problem?

Downgrading Contact form 7 to V 5.4.2 solved it for now.  

Maybe it has something to do with the code in contact-form-7/includes/contact-form-functions.php from line 226. In the picture the right side is V 5.4.2, left V 5.5.2
 
<img width="1183" alt="Schermafbeelding 2021-11-24 om 13 35 25" src="https://user-images.githubusercontent.com/6659380/143239513-6cc78c20-3c9b-42eb-b8a0-96a0a9684a3e.png">

Whould also like to hear about a fix.

**Comment by fixinggenie** [comment]
> > Any fix for this problem?
> 
> Downgrading Contact form 7 to V 5.4.2 solved it for now.
> 
> Maybe it has something to do with the code in contact-form-7/includes/contact-form-functions.php from line 226. In the picture the right side is V 5.4.2, left V 5.5.2
> 
> <img alt="Schermafbeelding 2021-11-24 om 13 35 25" width="1183" src="https://user-images.githubusercontent.com/6659380/143239513-6cc78c20-3c9b-42eb-b8a0-96a0a9684a3e.png">
> 
> Whould also like to hear about a fix.

I also downgraded. 

I don't know why it isn't seeing the user permissions for unfiltered_html. I checked and my user definitely has it.

**Comment by sstraus** [comment]
I need more tests, but I've fixed adding `stripslashes `before processing "json_template".

`$properties['json_template']      = isset( $_POST["json_template"] ) ? $_POST["json_template"] : '';`

and

`$qs_cf7_data_template = stripslashes($qs_cf7_data_json_template);`

**Comment by kennym** [comment]
Open a PR, or fork this project, and stop sending me emails. I've created this on a weekend; and now I don't have time to maintain this anymore. Thanks for understanding
