### ISSUE TITLE
Form is not saved

### ISSUE THREAD

**Issue by VincentSC** [kennym/cf7-to-api#48]
All data under tab “API Integration” is not being saved. I tried different browsers, but all I got was “Contact form saved” and an empty form.

What could be the cause? “max_input_vars” is 1000.

**Comment by mooksz** [comment]
Same

**Comment by VincentSC** [comment]
Putting it to 10000 did not work. https://wordpress.org/support/topic/form-is-not-saved/

**Comment by BurakBoz** [comment]
Same issue here. Nothing is saved any suggestions?

**Comment by eashman** [comment]
Same for me - it can be fixed temporarily by downgrading to Contact Form 7 v5.5.2 -- it appears some change in 5.5.3 is what broke this.

https://wordpress.org/plugins/contact-form-7/advanced/  and scroll to the bottom to get to older versions of the form plugin.

**Comment by VincentSC** [comment]
I can confirm this works. As suddenly test-data showed up, I _assume_ the data is actually saved but not shown in the form.

**Comment by AllCdnBoy** [comment]
WP has a plugin called "Rollback" which made the process of rolling back nice and easy.  I think if you haven't tried to re-save the API details, they will come back when you rollback

**Comment by VincentSC** [comment]
No need for that plugin. By manually uploading the old version, it also rolls back without problems.

I can say that the plugin stops working after an update to 5.5.3. So it needs to be held at 5.5.2 until this is fixed.

**Comment by AllCdnBoy** [comment]
Doesn't appear to always be the case. The was the first thing I tried and it said "This plugin already exists"

**Comment by VincentSC** [comment]
Click "Replace current with uploaded"

![image](https://user-images.githubusercontent.com/5090382/144651777-65bc9886-f027-45e3-a0d2-5c9d887452e4.png)

**Comment by AllCdnBoy** [comment]
I don't have those options. It goes from this:
![image](https://user-images.githubusercontent.com/13036861/144654625-b337dd48-6dba-4696-b93e-edb10d51c59f.png)
 
to this:

![image](https://user-images.githubusercontent.com/13036861/144654570-26955050-dfee-41c7-a3d1-6987eef5d51a.png)

**Comment by VincentSC** [comment]
Weird. No sure why there is a difference, assuming you also have the latest Wordpress version.

About this bug. When I've done my taxes, I'll spend some time to debug the problem. I found another plugin who had the same problem, so it can be done by example. If you cannot wait for my taxes, please be my guest. :)

https://wordpress.org/support/topic/the-plugin-isnt-working-with-new-version-of-cf7/
https://github.com/mariovalney/cf7-to-zapier

Main problem is to get a PR accepted, as maintenance is not really done here

**Comment by VincentSC** [comment]
Fixed! (yes, finished taxes)

Add one line to includes/class-cf7-api-admin.php on line 82, after `add_filter( "wpcf7_contact_form_properties" ,array( $this , "add_sf_properties" ) , 10 , 2 );`:
```
	add_filter( 'wpcf7_pre_construct_contact_form_properties', array( $this, 'add_sf_properties' ), 10, 2 );
```
That's all.

I'm not at my dev-machine, so cannot easily create a PR. So if you want it fixed now, you need to manually edit that file. I've already contacted the author some days ago, but did not get a response yet.

**Comment by mariovalney** [comment]
Thanks for the props @VincentSC :)

Actually the answer is in [CF7 release post](https://contactform7.com/2021/11/28/contact-form-7-553/#changes-on-contact-form-properties-handling). The problem is CF7 seems to do not follow [semantic versioning](https://semver.org/) and introduced a breaking change into a minor release.
