### ISSUE TITLE
cURL error 60: SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by mickmcg** [kennym/cf7-to-api#7]
I am getting this error when I POST to https://chloe.insightly.services/Forms/xyz123...

The suggestion for this error is always to download the cacert.pem file from:
https://curl.haxx.se/docs/caextract.html

Editing /etc/php.ini to set the curl cainfo parameter like this.

```
[curl]
curl.cainfo="/etc/pki/tls/cacert.pem"
```

But I have done this and restarted httpd I still get the same cURL error 60 every time.

**Comment by kennym** [comment]
This seems to be a problem with your local environment, let me know if you want to discuss this further.
