### ISSUE TITLE
Error line 595 of class-cf7-api-admin.php

### ISSUE THREAD

**Issue by Daniel-E-Davies** [kennym/cf7-to-api#9]
Typo says 'Basic ' instead of 'Bearer '

Secondly on the same line, the API key that I submit does not need to be base 64 encoded, it is already in the correct format. I hacked the line locally as follows. Not elegant but it works... For some reason removing the encoding all together created other errors.

$args['headers']['Authorization'] = 'Bearer ' . base64_decode(base64_encode( $bearer_auth ));

**Comment by kennym** [comment]
That's not a typo. It uses HTTP Basic Auth. If you need token authentication, which is what the example you posted does, feel free to submit a PR. :-)
